# Notes

## Research question 
The research question concerns whether people care whether what they believe is actually true? That is, do they value truth?

## Truth definition
What is truth? According to correspondence theory (Marian, 2016) truth corresponds with facts and empirical evidence. Although this could be disputed in a philosophical sense, we want to avoid this avenue by conceptualising facts in the general sense understood by the general public...

We want to measure the underlying construct which compels people to fact check news stories, or seek scientific information regarding the efficacy of horoscopes predicting/determining the future, and to seek that information in an impartial way on order to find the truth or the best evidence available. We are not concerned with value judgements, the ability to determine whether something is true or not, or whether a person holds predominantly true beliefs. We are concerned with their motivation to find the most objective and factual evidence. 

Given that beliefs are a matter of degree (ref), We are also concerned with whether people believe things a little bit (CLARIFY). 

Lynch (2004) argues that caring for truth is different from simply believing the truth. Truth can be acquired through no particular virtue of the individual, but caring about truth requires one to strive for truth; to put effort in. Lynch argues that to care about truth is to strive for truth behaviourally; to have a character orientated towards truth. This includes being open minded, questioning assumptions, and paying attention to detail. 
It also involves being intellectually virtuous which entails striving for truth across many domains. That is, not just listening to others when one is obliged to do so or for shame’s sake, but having a willingness to actively engage with others to ensure alternative perspectives have been considered and will change beliefs appropriately given evidence. Striving for truth in across all domains reflects that one values knowing the truth for the sake of it, rather than believing whatever helps achieve one’s goals. Must seek and be open to truth precisely because it is the truth.

Lynch argues caring for truth also manifests as a willingness to stand up for what you believe, not just when it is convenient, but even when it goes against the crowd. Must stand up for truth because it is right to do so, not just because a specific fact fits with your goals and motivations. “… a person of intellectual integrity stands for what she thinks is true precisely because she thinks it is true.” Hence, must pursue the truth overall, not just when it suits you. This contrasts with someone who believes/acts out of necessity to attain their goal, regardless of the truth. Hence, caring about truth means taking steps to avoid motivated reasoning. Lynch has outlined some characteristics of those who care about believing what is true and strive to attain that goal. 

## Questions

Measuring agreement with statements that reflect such behaviours could be used to assess the underlying construct, for example, ‘I try to fact check the stories I here in the news with reliable sources.’ However, behavioural measures pose a problem, see NFC in Related Scales.

Or perhaps we should avoid measuring behaviours which may add noise to participants’ responses. Could focus on attitudes towards truth, e.g., ‘I care about finding the truth for its own sake, not any practical purpose it could serve.’

This poses some questions, such as how much does the average person care about truth itself, compared with desiring accuracy as a means to an end? How can we disentangle believing what is true because it serves a practical purpose vs believing what is true based on an intrinsic value of truth? Do we want to?

Maybe we should control for the perception of the attainability of objective truth? (DeBacker, Crowson, Beesley, Thoma, & Hestevold, 2008; Schommer, 1994).

# Measuring motivated resoning: 
(need something that covers the main aspects of motivated reasoning, seeking, interpretation and evaluation of evidence?)

- Westen, D., Blagov, P. S., Harenski, K., Kilts, C., & Hamann, S. (2006). Neural bases of motivated reasoning: An fMRI study of emotional constraints on partisan political judgment in the 2004 US presidential election. Journal of cognitive neuroscience, 18(11), 1947-1958.
Measured ability to admit that the politician they support made contradictory statements.

- Mullen, E., & Skitka, L. J. (2006). Exploring the psychological underpinnings of the moral mandate effect: Motivated reasoning, group differentiation, or anger?. Journal of personality and social psychology, 90(4), 629.
Measured opinions of a person on trial who was either very similar or dissilamr to themselves.

- Dawson, E., Gilovich, T., & Regan, D. T. (2002). Motivated Reasoning and Performance on the Wason Selection Task. Personality and Social Psychology Bulletin, 28(10), 1379-1387.
"The stereotype that the Irish tend to like their drink was
transformed into a Wasonrule,“AllIrisharealcoholics.” Some participants tested a rule that, if true, implied
something negative about themselves", in which case they would be motivated to falsify it.


# What else should it correlate with? 
- Bullshit Receptivity Scale (BRS). Pennycook, Cheyne, Barr, Koehler, and Fugelsang (2015).
- Belief in Science Scale (BSS). (Farias, Newheiser, Kahane, & de Toledo, 2013).  
- Rosenbery Self-esteem scale??? Martín-Albo, J., Núñez, J. L., Navarro, J. G., & Grijalvo, F. (2007). The Rosenberg Self-Esteem Scale: translation and validation in university students. The Spanish journal of psychology, 10(02), 458-467.
- Attitudes  and  Beliefs  Scale  2 (DiGiuseppe  et  al.,  1988): measures irrational beliefs. The ABS2 is a 72-item scale consisting of a 4x3x2 matrix. The   first   factor   consists   of   belief   processes   and   has   four   levels   representing   demandingness   (DEM),   self-worth   or   self-downing   (SD),   low   frustration  tolerance  (LFT)  and  awfulizing  (AWF).  The  second  factor  includes  content/context  information  and  has  three  levels  representing  beliefs  about  affiliation,  achievement  and  comfort.  The  third  factor  determines  if  the  item  is  worded   rationally   or   irrationally.  
- Belief in good luck scale.  Darke, P. R., & Freedman, J. L. (1997). The belief in good luck scale. Journal of Research in Personality, 31(4), 486-511.
- Magical Ideation Scale (MI Scale; Eckblad & Chapman, 1983)


# Irrational beliefs and positive affect/stress relief literature:
- Keinan, G. (1994). Effects of stress and tolerance of ambiguity on magical thinking. Journal of personality and social psychology, 67(1), 48.
- Darke, P. R., & Freedman, J. L. (1997). The belief in good luck scale. Journal of Research in Personality, 31(4), 486-511.
- King, L. A., Burton, C. M., Hicks, J. A., & Drigotas, S. M. (2007). Ghosts, UFOs, and magic: positive affect and the experiential system. Journal of personality and social psychology, 92(5), 905.
- Wiseman, R., & Watt, C. (2004). Measuring superstitious belief: Why lucky charms matter. Personality and Individual Differences, 37(8), 1533-1541.
- Markle, D. T. (2010). The magic that binds us: Magical thinking and inclusive fitness. Journal of Social, Evolutionary, and Cultural Psychology, 4(1), 18.
- Berenbaum, H., Boden, M. T., & Baker, J. P. (2009). Emotional salience, emotional awareness, peculiar beliefs, and magical thinking. Emotion, 9(2), 197-205. doi:10.1037/a0015395