# Truth Value Scale

- I strive to believe what is true. 
- I never make conclusions until I have sufficient evidence.
- I believe some things because they are fun, it does not really matter whether they are true or not. R
- I try to fact check the stories I here in the news with reliable sources. 
- I only need to believe what is true so that I can live my life as I want. R
- I do not care about the exact truth, if I have sufficient knowledge/understanding to live my life. R
- I care about finding the truth for its own sake, not any practical purpose it could serve.
- I believe things that make me feel good, even if that’s not exactly objective reality. R
- I probably believe somethings because it’s convenient, especially if the subject is trivial.
- I like to do my own reading on topics, rather than accept what others around me believe.
- It is ok to believe something if it makes you feel better about the world, even if it’s not completely true. R
- It’s ok to believe something if it leads you to do something good for yourself or others, even if it’s not true. R
- Everyone has their own truth, things that they believe is right. R
h- Truth is constant and universal, it doesn’t matter what you were raised to believe. 
- I acknowledge that I am biased.
- I try to think of how my bias influences my decisions in order to overcome them. 